### ISSUE TITLE
Read defaults from package.json

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2-manifest#1]
For many apps it's useful to be able to automatically generate `manifest.json` based on `package.json`.

If `package.json` exists, it's probably a good idea to automatically use values from that file as defaults.

The following standard fields from `package.json` can be used by default:

`name`
`description`
`version` - which also means the version number can be controlled with [`npm version`](https://docs.npmjs.com/cli/version)
`author` (can be [a string or an object](https://docs.npmjs.com/files/package.json#people-fields-author-contributors))

Secondly if `package.json` contains a key called `"webapp.manifest"`, the value of this key should be merged into the destination `webapp.manifest`, overriding any existing values.

If `package.json` contains the following:

``` json
{
  "name": "My Sample App",
  "version": "1.2.3",
  "description": "A sample application",
  "author": "Nicolay Ramm <nicolay@dhis2.org>",
  "webapp.manifest": {
    "launch_path": "index.html",
    "icons": {
      "48": "img/48.png"
    }
  }
}
```

The following `webapp.manifest` would be generated:

``` js
{
  "version": "1.2.3", // "version" in package.json
  "name": "My Sample App", // "name" in package.json
  "description": "A sample application", // "description" in package.json
  "default_locale": "en", // default value
  "developer": { // "author" in package.json
    "name": "Nicolay Ramm", // parsed from the "author" string
    "email": "nicolay@dhis2.org" // parsed from the "author" string
  },
  "icons": { // "webapp.manifest.icons" in package.json
    "48": "img/48.png"
  },
  "activities": { // default value
    "dhis": {
      "href": "*",
    }
  }
}
```

**Comment by Markionium** [comment]
Very nice.

When editing the `pom.xml` file while writing the guide for the `mvn deploy` workflow. I realised that we might also generate that from the same package.json

@see https://github.com/dhis2/dhis2-apps-docs

I guess this would sort of go passed the `d2-manifest` scope, but perhaps we can rebrand it to `d2-cli` or w/e.

**Comment by nicolayr** [comment]
Yes, we could do that. But is there anything other than `${apps.version}` that needs to be updated on a regular basis in `pom.xml`? If not, it might be a tad overkill.

**Comment by Markionium** [comment]
It's more a nice to have rather than a thing we should do right away. But i think if we can automate some of that copy-paste stuff when "bootstrapping" an app, that'd be nice. The benefit would primarily be in getting it right on the initial go, other than having to manually copy/edit the thing each time.

Not just for us but for the larger community also. But not a priority for now :)

**Comment by nicolayr** [comment]
Done!
