### ISSUE TITLE
Adjust for new appType field in the manifest

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2-manifest#11]
For `2.22` and up we should support modifying the `appType` property in the manifest.

The appType property can contain one of four values
- APP (default)
- RESOURCE
- DASHBOARD_WIDGET
- TRACKER_DASHBOARD_WIDGET

``` js
// manifest.webapp 
...
"appType": "DASHBOARD_WIDGET",
...
```

**Comment by mortenoh** [comment]
Hi Mark,

Are we ok with these constants or not? please reply to original email.

## 

Morten Olav Hansen
Senior Engineer, DHIS 2
University of Oslo
http://www.dhis2.org
