### ISSUE TITLE
Add `manifest_generated_at` timestamp to the manifest

### ISSUE THREAD

**Issue by nicolayr** [dhis2/d2-manifest#3]
In order to get even more fine grained version information, it would be nice to include a timestamp that indicates when the manifest was generated.
- The timestamp needs to include timezone information
- The timestamp should parse properly with `new Date(timestamp)`
- There should be a (boolean) command line flag to disable the timestamp, such as `--no-timestamp`

**Comment by shiveeg1** [comment]
I would like to fix this issue.

**Comment by mortenoh** [comment]
I'm not sure if your use case is 100% the same, but this is our internally
generated cache manifest:

CACHE MANIFEST

# <version> $!systemInfo.revision

# appcache for user: $username

# system calendar: $keyCalendar

Depending on how you are using the cache, you might need to redownload in
all these cases. This is especially true for OUWT offline support (idb).

On Fri, Mar 11, 2016 at 9:45 PM, Shivee Gupta notifications@github.com
wrote:

> I would like to fix this issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dhis2/d2-manifest/issues/3#issuecomment-195395951.

## 

Morten

**Comment by shiveeg1** [comment]
I have created a [pull request](https://github.com/dhis2/d2-manifest/pull/6) for this issue. Please review.

**Comment by nicolayr** [comment]
@mortenoh this is about knowing which version/build of the front end apps people are using for debugging purposes, so not really related to caching. But thanks for the heads up :)
